events {}

http {
    upstream users {  server users-service:3001; }
    upstream products { server products-service:3002; }
    upstream orders { server orders-service:3003; }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://users;
            rewrite ^/api/users(.*)$ /users$1 break;
        }

        location /api/products {
            proxy_pass http://products;
            rewrite ^/api/products(.*)$ /products$1 break;
        }

        location /api/orders {
            proxy_pass http://orders;
            rewrite ^/api/orders(.*)$ /orders$1 break;
        }

        location / {
            return 200 '{"services": ["/api/users", "/api/products", "/api/orders"]}';
            add_header Content-Type application/json;
        }
    }
}
